import{a as q,S as P,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const R="https://pixabay.com/api/",$="50807386-01a9bb8c8dc5d7c785d84b37d",B=15;async function p(t,o=1){const r={key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:B,page:o};return(await q.get(R,{params:r})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".load-more"),y=document.querySelector(".top-loader"),g=document.querySelector(".bottom-loader");let u="top";function L(t){u=t}const M=new P(".gallery a",{captionDelay:250,captionsData:"alt"});function b(t){const o=t.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><span>Likes:</span> ${r.likes}</p>
        <p><span>Views:</span> ${r.views}</p>
        <p><span>Comments:</span> ${r.comments}</p>
        <p><span>Downloads:</span> ${r.downloads}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",o),M.refresh()}function O(){m.innerHTML=""}function w(){u==="top"?y.classList.remove("hidden"):g.classList.remove("hidden")}function i(){u==="top"?y.classList.add("hidden"):g.classList.add("hidden")}function v(){h.classList.remove("hidden")}function C(){h.classList.add("hidden")}const S=document.querySelector(".form"),x=S.elements["search-text"],k=document.querySelector(".load-more");let l="",n=1,f=0;S.addEventListener("submit",async t=>{if(t.preventDefault(),l=x.value.trim(),n=1,O(),C(),i(),l===""){a.error({title:"Error",message:"Please enter a search query.",position:"topRight",timeout:3e3,backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff"});return}L("top"),w();try{const o=await p(l,n);if(o.hits.length===0){i(),a.warning({title:"Sorry",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3,backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff"});return}b(o.hits),f=Math.ceil(o.totalHits/15),n<f&&v()}catch{a.error({message:"Fetch error.",position:"topRight"})}finally{i()}});k.addEventListener("click",async()=>{n+=1,L("bottom"),w(),C();try{const t=await p(l,n);b(t.hits),D(),n<f?v():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff"})}catch{a.error({message:"Fetch error.",position:"topRight",backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff"})}finally{i()}});function D(){const t=document.querySelector(".gallery-item");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
